### ISSUE TITLE
Add X and Y coordinates

### ISSUE THREAD

**Issue by vpetersson** [NebraLtd/LoRa-mPCIe#10]
The manufacturing site is asking to update these files to make sure they include X and Y coordinates in the drawings. This is apparently blocking them from moving forward.

**Comment by shawaj** [comment]
All here https://github.com/NebraLtd/LoRa-mPCIe/tree/v1.1/hardware/Outputs/Assembly

**Comment by shawaj** [comment]
Sent to factory
[LoRa-mPCIe-1.1.zip](https://github.com/NebraLtd/LoRa-mPCIe/files/7023563/LoRa-mPCIe-1.1.zip)
